apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orca-readonly
  labels:
    app.kubernetes.io/name: orca
subjects:
  - kind: ServiceAccount
    name: orca
    namespace: orca-system
roleRef:
  kind: ClusterRole
  name: orca-readonly
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orca-operator
  labels:
    app.kubernetes.io/name: orca
subjects:
  - kind: ServiceAccount
    name: orca
    namespace: orca-system
roleRef:
  kind: ClusterRole
  name: orca-operator
  apiGroup: rbac.authorization.k8s.io
